### ISSUE TITLE
some Zanetti File numbers missing in TEI

### ISSUE THREAD

**Issue by nathangibson** [srophe/persons#2]
Some of the TEI files are missing some of the Zanetti numbers. See, for example, http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1113/tei which should have an <idno type='BHSYRE'>346</idno> but doesn't. We think the problem is this line https://github.com/srophe/persons/blob/master/xsl/saint-spreadsheet2tei.xsl#L292 but Dave and I can't quite decipher it. So we're renaming the unnamed columns BK-BW as "Fiche" so that the XSL can catch them easier.

**Comment by wsalesky** [comment]
So what should be showing here?
There are the following rows:
Zanetti_Numbers:
 346,347,348,350,351,352,353,354,355,356,357,358,359,360,361,176,704

Z1__Zanetti_Files_:
176,346,347,348,350,351,352,353,354,355,356,357,358,359,360,361,704

Z1_: 176

Zanetti_Files: 346

Heading62 - Heading76 (which all have values)

The reason the current xslt is coming up empty is because it is a bad regex (my bad!) it looks for only numbers, and of course these have commas. Although the second part of the select should work, so I will have to take a closer look at that.

**Comment by davidamichelson** [comment]
If you look in the google doc version of the sheet "Saints Canonical" the
columns we want are now each called "Fiche" so the for each can just grab
their values.

**Comment by wsalesky** [comment]
Okay. In that case the for each should just be changed to look like this: 
&lt;xsl:for-each select="Fiche"&gt;
                &lt;idno type="BHSYRE"&gt;&lt;xsl:value-of select="."/&gt;&lt;/idno&gt;
&lt;/xsl:for-each&gt;

Would you like me to rerun the data?
-Winona

**Comment by wsalesky** [comment]
See commit 4326f6

**Comment by davidamichelson** [comment]
@wsalesky Where is this new data? I don't see it in Draft Data repository.

**Comment by davidamichelson** [comment]
Okay, I found it here I think? https://github.com/srophe/persons/tree/master/new-saints-data/new-saints/tei

Is that correct?

**Comment by wsalesky** [comment]
Yes, it is there, but I thought I pushed a copy to draft data... Just
checked and I did not. Doing it now.
-Winona

**Comment by davidamichelson** [comment]
Okay, great I'll work off of the draft data one.

**Comment by wsalesky** [comment]
Okay, should be up now.
-Winona

**Comment by davidamichelson** [comment]
Thanks!
